### ISSUE TITLE
Please clarify why Nuts is not a solution

### ISSUE THREAD

**Issue by develar** [Aluxian/squirrel-updates-server#1]
Why you decided to write own server if there is https://github.com/GitbookIO/nuts ?

**Comment by Aluxian** [comment]
1. I had a poor experience with the way Nuts worked (as far as I can remember, it didn't sync properly with GitHub)
2. For Linux packages, there wasn't a way (or, at least, I couldn't find it) to specify which package type I wanted (deb or rpm) and for which arch
3. I was confused by how it "automagically" served assets for each platform (hence, issue no. 2 above)
