### ISSUE TITLE
Any functional example in electron?

### ISSUE THREAD

**Issue by Samuell1** [Aluxian/squirrel-updates-server#12]

**Comment by Aluxian** [comment]
Here's one: https://github.com/Aluxian/Messenger-for-Desktop

That's all I have. Maybe others can mention their own.

**Comment by Samuell1** [comment]
Thanks for example! Its very good but i dont understand what url i need to set for autoUpdater.setFeedUrl. Can you create more detailed doc table what url is best for OS?

**Comment by Aluxian** [comment]
See `updater` here: https://github.com/Aluxian/Messenger-for-Desktop/blob/master/src/package.json

`{{& SQUIRREL_UPDATES_URL }}` is the url to this server, e.g. `updates.mfd.com`.

`%CHANNEL%` and `%CURRENT_VERSION%` are replaced here: https://github.com/Aluxian/Messenger-for-Desktop/blob/master/src/scripts/browser/managers/auto-update-manager.js#L49

**Comment by Samuell1** [comment]
I try that url but i have some weird error, any idea what i need to change? or github changed api?

http://localhost/update/win32/app-0.0.4-full.nupkg
```
{
    "error": "{\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3\"}",
    "sid": "9ba9273948434922891740f74b3a456c"
}
```

**Comment by Aluxian** [comment]
Try to add an env var `GITHUB_TOKEN` to the server (create one here: https://github.com/settings/tokens). `Not Found` is sometimes `not authorized`.

**Comment by kurtulik** [comment]
Token is ok.. when i tray orher files et. Portable is download succes only when files get name with version number this is fail.

**Comment by Samuell1** [comment]
@Aluxian i try private and public repo same error. if i remove version 0.0.4 its working

**Comment by Samuell1** [comment]
@Aluxian i dont need change patterns with version?

```
win32: {
      installer: /-win32-setup\.exe/,
      zip: /-win32-portable\.zip/
},
```

**Comment by Samuell1** [comment]
I find it i need to have tag version on github with v0.0.4 i have only 0.0.4 ✌️

**Comment by Aluxian** [comment]
I added a notice in the README. Hopefully, this will help new people.
