### ISSUE TITLE
Which permissions are required for the Github token when using a private repo?

### ISSUE THREAD

**Issue by petebytes** [Aluxian/squirrel-updates-server#20]
Server running in dev environment trying to access private repo

When I browse the following URL
http://localhost:3000/update/darwin?version=v1.0.0

Receive the following
{"error":"{\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3\"}"}

My token permissions are set with all the "repo" settings.

**Comment by aluxian** [comment]
The repo permissions should be enough. Are you sure everything else is fine? Try to make a new public repo, set it up so everything works, make it private, check if everything still works, then finally switch to your real repo. 

--

Alexandru Rosianu
Co-founder & CTO — futuristico.xyz

**Comment by petebytes** [comment]
Thanks for the quick response and this project!

No I am not sure :) will try to isolate the issue as you recommended

**Comment by petebytes** [comment]
No luck with public repo either.

- Created the repo
- Created a release tagged v1.0.0
- Added a file to the release testme-osx.zip
- copied in the base config.js to the squirrel-updates-server/src folder
- modified the repo and user info in the config.js

If you have time to look, the repo is https://github.com/CodePilotai/auto-update-test
I have the config.js I am using in the repo

**Comment by petebytes** [comment]
here is how I have the release configured
https://github.com/CodePilotai/auto-update-test/releases

**Comment by petebytes** [comment]
I have both public and private repos working.
user config settings issue.

Thanks
