### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by mzmousa** [Aluxian/squirrel-updates-server#4]
Babel-CLI, core-js, and a few other modules were not properly installed when I tried to do do ```npm run build```. After installing the first two I mentioned, I got the error ``` Error: Cannot find module '../lang/isArguments' ```, so I think ```npm install``` did not work correctly. I am running git bash on windows

**Comment by Aluxian** [comment]
I cloned the repo and did a clean `npm install` followed by `npm run build` and it worked perfectly. What is your npm/node version? Can you update npm and node to the latest versions and then try another clean install? I have npm n3.6.0 and node v5.6.0.

**Comment by mzmousa** [comment]
Great. Just worked after I updated my npm and node versions, thanks.  
This is kind of off topic but is this meant to be a replacement for the checkForUpdates() method for [autoUpdater](http://electron.atom.io/docs/latest/api/auto-updater/) ? I'm trying to get updates for my app working and having a lot of trouble, if you know anything about that. I got the grunt-electron-installer working fine, but the updates and squirrel.windows are a mess for me

**Comment by Aluxian** [comment]
This server is supposed to work *with* autoUpdater. I have included some details about it in the README. View one of my apps to see how I use it: http://github.com/Aluxian/Whatsie

**Comment by mzmousa** [comment]
I have some questions about how the update mechanism works as I'm trying to implement one myself - would you have time for that & should I post my question(s) on Whatsie/issues ?

**Comment by Aluxian** [comment]
I wouldn't have time, sorry. I recommend you join the official Electron Slack channel and ask there for help.
