### ISSUE TITLE
/stats

### ISSUE THREAD

**Issue by atdrago** [Aluxian/squirrel-updates-server#7]
Hello and thanks for this product. Setup was pretty easy. :)

I'm getting an error with trying to view `/stats`:

```json
{"error":"Cannot read property 'installer' of undefined"}
```

Just wondering if you've seen this before. From http://squirrel.negativeapp.com/stats

**Comment by Aluxian** [comment]
Something must be wrong in [this](https://github.com/Aluxian/squirrel-updates-server/blob/master/src/components/stats.js) file, then.

The status code returned is 500, can you please add the following line of code [here](https://github.com/Aluxian/squirrel-updates-server/blob/master/src/components/utils.js#L27):

```
console.log(err.stack);
```

What does it print?

**Comment by Aluxian** [comment]
Also, do you have the `patterns.win32` object [in config](https://github.com/Aluxian/squirrel-updates-server/blob/master/src/config.js)? That might also be a cause for the error.

**Comment by atdrago** [comment]
Sorry for the delay in my response!

> Also, do you have the `patterns.win32` object in config? That might also be a cause for the error.

No, I don't. My app only supports macOS right now. `patterns.win32` should probably not be required, right?

Here's my setup: https://github.com/atdrago/squirrel-updates-server

**Comment by Aluxian** [comment]
We found the problem, then. I'll update the code to exclude win 32 if its pattern is missing. Until then, you can make the server work by adding all patterns back in config.


--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Wed, Jul 06, 2016 at 4:05 AM, Adam Drago < notifications@github.com [notifications@github.com] > wrote:
Sorry for the delay in my response!

Also, do you have the patterns.win32 object in config? That might also be a cause for the error.

No, I don't. My app only supports macOS right now. patterns.win32 should probably not be required, right?

Here's my setup: https://github.com/atdrago/squirrel-updates-server [https://github.com/atdrago/squirrel-updates-server]
